### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by NayamAmarshe** [upscayl/upscayl#5]
- [ ] #79
- [ ] [HELP WANTED] Release on Flathub #133
- [ ] Paste Image URI from clipboard #108 
- [ ] #77
- [ ] Localization?
- [ ] Compile on Mojave/Big Sur? #98 
- [ ] Add Real-CUGAN #86 
- [x] Update flatpak runtime to 22.08
- [x] Add Remacri Model as main model #107
- [x] Add multi-format save options #120 
- [x] Add GPU selection counter #123 
- [x] #78
- [x] Store settings in localstorage
- [x] Provide DEBs #134 
- [x] Add Wayland options #76 
- [x] Add Windows install path option
- [x] Fix BSRGAN model implementation
- [x] Fix PNG bottom info overlay bug
- [x] Fix empty upscale bug #18
- [x] Add drag and drop support #19
- [x] Add Copy-Paste functionality #25 
- [x] Show a no GPU warning #14
- [x] Scale Factor Functionality
- [x] Model Selection
- [x] Output Destination Select
- [x] Live Image Comparison
- [x] Save Image after upscaling functionality
- [x] Show Progress Percentage
- [x] #13
- [x] #8
- [x] #50
- [x] Add Real-SRGAN Denoising options #11

**Comment by aaronliu0130** [comment]
Maybe this should be migrated to projects

**Comment by NayamAmarshe** [comment]
> Maybe this should be migrated to projects

I like it better this way, easier to access and manage.

**Comment by aaronliu0130** [comment]
I think using github projects is better since it is easier to access them from linked issues, you can set milestones to them, and you can set the status and progress on it. It's also easier to edit and sort things there.

**Comment by NayamAmarshe** [comment]
> I think using github projects is better since it is easier to access them from linked issues, you can set milestones to them, and you can set the status and progress on it. It's also easier to edit and sort things there.

I know, I've used them before extensively but I honestly believe the issues workflow is better and faster, especially for a project of this size :)

**Comment by rufreakde** [comment]
hey I saw the TODO list and had a question to:
`Allow Video Upscaling, detect ext and set model accordingly`
will it be a CLI command where you pass a video file and an output file? Or is it also a UI thing?
Could write a bash script with it later on with such a functionality.

Very nice project! Directly Starred :)

**Comment by TGS963** [comment]
> will it be a CLI command where you pass a video file and an output file? Or is it also a UI thing?

It will be a UI thing. We have already provided CLI binaries with their models in the resources folder. Those binaries can be directly used from CLI and video upscaling is already present in those as they are taken from REAL-ESRGAN. The video upscaling in the to-do list refers to the UI implementation that isn't present yet.

Thanks for the star :)

**Comment by rufreakde** [comment]
Sorry I see the FAQ just now!
`Is there a CLI available?
The CLI tool is called real-esrgan-ncnn-vulkan and it's available on the Real-ESRGAN repository.` :)

**Comment by Jonas1999** [comment]
I really like this project, don't know if this is the place you want us to suggest changes/improvements but I'll put it here for now.
Some of these things I might help with and commit myself to the project in my spare time.

- Have a toggle for replacing or skipping images with same name in target folder, if present
- Show progress of total images processed in batch mode
- (if possible) Remember last Input and Output folders individually
- Pause/Resume/Cancel buttons for batch jobs
- Select scaling factor in batch mode (2x, 4x, 8x for example)

**Comment by aaronliu0130** [comment]
To suggest changes, you would usually open new issues.

**Comment by aaronliu0130** [comment]
I guess we've migrated to https://github.com/orgs/upscayl/projects/1 !

**Comment by aaronliu0130** [comment]
@NayamAmarshe Should we use milestones instead of version issue labels?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Should we use milestones instead of version issue labels?

Are you talking about this issue? We're not using this To-Do list anymore😅

**Comment by aaronliu0130** [comment]
I know, I"m talking about this GitHub feature called milestones. I think using version number issue labels is a bit confusing, and milestones can save the same purpose.

**Comment by NayamAmarshe** [comment]
> I know, I"m talking about this GitHub feature called milestones. I think using version number issue labels is a bit confusing, and milestones can save the same purpose.

I'll take a look, thanks for the suggestion!
